points:
  key:
    width: cx
    height: cy
    spread: cx
    padding: cy
    bind: 1
  zones:
    main:
      columns:
        pinkie:
          key:
            splay: 14.89
            origin: [0,0]
            bind: [1, 30, 1, 1]
          rows:
            bottom.pin_net: P10
            center.pin_net: P5
            top.pin_net: P1
        ring:
          key:
            splay: -14.89
            spread: 20.066
            stagger: 4.328
            bind: [1, 20, 1, 1]
          rows:
            bottom.pin_net: P14
            center.pin_net: P6
            top.pin_net: P0
        midlle:
          key:
            splay: -7.55
            spread: 19.25 
            stagger: 4.452 
            bind: [1, 1, 9.5, 1]
          rows:
            bottom.pin_net: P15
            center.pin_net: P7
            top.pin_net: P2
        index:
          key:
            splay: -7.81
            spread: 18.92
            stagger: -4.985
            bind: [1, 1, 1, 20]
          rows:
            bottom.pin_net: P16
            center.pin_net: P8
            top.pin_net: P3
        farindex:
          key:
            splay: 0
            spread: cx
            stagger: -1.62
            bind: [1, 1, 10, 1]
          rows:
            bottom.pin_net: P18
            center.pin_net: P9
            top.pin_net: P4
    thumbcluster:
      anchor:
        ref: main_pinkie_bottom
        shift: [64.53, -41.89]
        rotate: -32.99
      columns:
        thumbleft:
          key:
            bind: [1, 1, 1, 1]
          rows:
            one.pin_net: P20
        thumbright:
          key:
            splay: -3.2
            spread: 18.48
            stagger: -4.675
            bind: [1, 1, 1, 10]
          rows:
            one.pin_net: P21

outlines:
  keycaps:
    - what: rectangle
      where: true
      size: [cx, cy]
      operation: stack
  mcu:
    - what: rectangle
      where:
        ref: main_farindex_bottom
        shift: [cx/2+17.78/2+3, -33/2+cy/2+2*cy]
      size: [17.78, 33]
  elements:
    - what: outline
      name: keycaps
      operation: stack
    - what: outline
      name: mcu
      operation: stack
  raw:
    - what: rectangle
      where: true
      bound: true
      size: [cx, cy]
    # add keys and MCU for debugging
    #- what: outline
    #  name: elements
    #  operation: stack
  first:
    # big bottom rectangle
    - what: rectangle
      where: 
        ref: main_pinkie_bottom
        orient: -33
        shift: [38.5, -1.35]
      size: [83.5, 24]
    # small rectangle for covering hole
    - what: rectangle
      where: 
        ref: main_pinkie_bottom
        orient: -33
        shift: [58.5, 10.35]
      size: [30.5, 10]
    # rectangle for MCU
    - what: rectangle
      where:
        ref: main_farindex_bottom
        shift: [cx, 7]
      size: [22+4, 73]
    # polygon for the keycaps
    - what: outline
      name: raw
      operation: add
    # small imperfection in thumb cluster
    - what: rectangle
      where: 
        ref: thumbcluster_thumbleft_one
        shift: [-5,-cy/2-5-1]
      size: [25,10]
      operation: subtract
    # bottom circle for aesthetics
    - what: circle
      where:
        shift: [14,-69]
      radius: 61
      operation: subtract
    # add keys and MCU for debugging
    #- what: outline
    #  name: elements
    #  operation: stack
  second:
    - what: outline
      name: first
      expand: 1
      joints: 0
    # add keys and MCU for debugging
    #- what: outline
    #  name: elements
    #  operation: stack
    
pcbs:
  main_pcb:
    outlines:
      main:
        outline: second
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          from: "{{pin_net}}"
          to: GND
          keycaps: true
          hotswap: true
          reverse: true # reversible
      microcontroller:
        what: mcu_supermini_nrf52840
        where:
          ref: main_farindex_bottom
          shift: [cx/2+17.78/2+3, -33/2+cy/2+2*cy]
      mounting_hole_1:
        what: mounting_hole_plated
        where:
          shift: [4.1, 39]
      mounting_hole_2:
        what: mounting_hole_plated
        where:
          shift: [14, -2.75]
      mounting_hole_3:
        what: mounting_hole_plated
        where:
          shift: [54, 46.5]
      mounting_hole_4:
        what: mounting_hole_plated
        where:
          shift: [59.5, -24.5]
      mounting_hole_5:
        what: mounting_hole_plated
        where:
          shift: [95.5, -23.75]
      mounting_hole_6:
        what: mounting_hole_plated
        where:
          shift: [86, 0.75]
      battery_connector:
        what: battery_connector_jst_ph_2
        where:
          ref: main_farindex_bottom
          shift: [cx/2+17.78/2+1.5, 0]
          rotate: 180
        params:
          BAT_P: PWR_SW
          #reversible: true # not needed because the pads have holes
      reset_switch:
        what: wuerth-434121025816
        where:
          ref: main_farindex_bottom
          shift: [cx/2+17.78/2+1.5, -7]
        params:
          r1: GND
          r2: RST
      power_switch:
        what: power_switch_smd_side
        where: 
          ref: main_farindex_bottom
          shift: [30.1, 0]
        params:
          from: RAW
          to: PWR_SW
          reversible: true
